name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql
          coverage: pcov
          tools: composer

      - name: Setting environment
        run: |
          echo "DATABASE_URL=pgsql://pguser:pguser@postgres:5432/study_on" >> .env.local
          composer install --no-interaction --prefer-dist

      - name: Setting Docker
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          mkdir ~/.yarn
          docker network create study-onbilling_default || true
          docker-compose build
          docker-compose up -d
          docker-compose exec -T php composer install --no-interaction --prefer-dist
          docker-compose run --rm -u root --entrypoint sh node -lc "npm install -g yarn && yarn install && yarn encore dev"
          docker ps -a

      - name: Setting test environment and DB
        run: |
          echo "DATABASE_URL=pgsql://pguser:pguser@postgres:5432/study_on" >> .env.test.local
          docker-compose exec -T php php bin/console doctrine:database:drop --force --env=test || true
          docker-compose exec -T php php bin/console doctrine:database:create --env=test
          docker-compose exec -T php php bin/console doctrine:migrations:migrate -n --env=test
          docker-compose exec -T php php bin/console doctrine:fixtures:load -n --env=test

      - name: Run PHPUnit
        run: |
          docker-compose exec -T php php bin/phpunit